# Create Factions
factions = Faction.create!([
  {id: "1", fac_name: "Crew"},
  {id: "2", fac_name: "Passengers"},
  ])

#Create Narrative
narratives = Narrative.create!([
  {heading: "Overview", content: "In early August in 1914 the American cruise liner SS Libertania set sail from New York, bound for Southampton. On 14 August the Captain requested that all crew and passengers meet him in the Grand Ballroom. In solemn tones, Captain Bayard announced that he had just been informed that German military forces had invaded Russia and Belgium, and that the British and French governments had declared war on Germany.\n\nThere was stunned silence from the assembled passengers and crew. Then, just as voices were getting louder, the lights went out. There were screams, and a shot. By the time the lights came on again, many people had left the ballroom and the Captain’s body was slumped on the floor. He had been shot dead.\n\nBut by whom?\n\nMurder at Sea is a murder mystery game set at the start of the First World War for 17 to 33 players, plus one or two hosts. It takes an evening to play, and is ideally suited for a buffet meal or finger food.\n\nEveryone invited to Murder at Sea is given a character with goals and objectives that they must complete by the end of the evening. Everyone has their own goals – and not all goals are compatible. If one person achieves their goals, another may fail. The passengers have various items, such as guns and money. They may also have abilities to help them uncover secrets and achieve their goals.\n\nThe passengers may form alliances, blackmail each other, steal items and money and maybe even try to kill one another. Along the way they may solve some of Murder at Sea’s mysteries. Who was at the secret Captain’s meeting? Who shot Captain Bayard – and why?\n\nJoin us aboard the Libertania and find out in Murder at Sea."},
  ])

# Create Characters
users = User.create!([
  {email: "kal444h@gmail.com", password: "asdf123", faction_id: "1", role: "admin", attendee: "Kirk Lansman", position: "game_master", character: "Tiberius", title: "mysterious host", tagline: "heyyyyy"},
  {email: "siconninja@gmail.com", password: "asdf123", faction_id: "1", role: "admin", attendee: "Carmine Iannacone", position: "game_master", character: "Sicon", title: "mysterious host", tagline: "schweet"},
  {email: "a@email.com", password: "floor", faction_id: "1", role: "member", attendee: "party guest", position: "First Officer", character: "Daniel Warren", title: "35, American", tagline: "Competent First Officer, well liked by the crew and expected to be given command of a ship as soon as possible. Reports to the Captain."},
  {email: "b@email.com", password: "seat", faction_id: "1", role: "member",  attendee: "party guest",position: "Second Officer", character: "David Whitworth", title: "47, English", tagline: "Reliable and competent officer, previously sailed with the Royal Merchant Navy. Reports to the First Officer."},
  {email: "c@email.com", password: "watch", faction_id: "1", role: "member",  attendee: "party guest",position: "Third Officer", character: "Christina Younger", title: "36, American", tagline: "The highest placed woman in the Cruise Line and has sacrificed her personal life for her career. Reports to the Second Officer."},
  {email: "aerocricket@gmail.com", password: "mur_maid", faction_id: "1", role: "member", attendee: "David Atwater", position: "Entertainments Officer", character: "Vic Hammerstein", title: "49, American", tagline: "Always provides lavish entertainment spectaculars for passengers. Reports to the First Officer."},
  {email: "d@email.com", password: "ladybug", faction_id: "1", role: "member", attendee: "party guest", position: "Master Chef", character: "Blaise de Richelieu", title: "50, French", tagline: "Temperamental culinary genius, signed on by Hammerstein at great expense. This is de Richelieu’s first voyage aboard the Libertania, and so far the cuisine is not up to expectations. Reports to the Third Officer."},
  {email: "e@email.com", password: "error", faction_id: "1", role: "member", attendee: "party guest", position: "Cocktail Stewardess", character: "Julia Morteblanca", title: "25, Italian", tagline: "Previously worked in the Waldorf Astoria as America’s first professional female cocktail mixer. Reports to the Chief Purser."},
  {email: "f@email.com", password: "carport", faction_id: "1", role: "member", attendee: "party guest", position: "Cabin Stewardess", character: "Catherine New", title: "18, English", tagline: "Only recently joined the Libertainia, but already knows everything about anything on board the ship. Reports to the Chief Purser."},
  {email: "g@email.com", password: "squirrel", faction_id: "1", role: "member", attendee: "party guest", position: "Cabin Stewardess", character: "Cynthia Petal", title: "32", tagline: "Has been working aboard liners for half of her life, and is competent and well liked by crew and passengers. Reports to the Chief Purser."},
  {email: "h@email.com", password: "weather", faction_id: "1", role: "member", attendee: "party guest", position: "Trainee Steward", character: "Eric Lassiter", title: "20, Scottish", tagline: "Training to be a steward. Reports to the Chief Purser."},
  {email: "i@email.com", password: "temper", faction_id: "1", role: "member", attendee: "party guest", position: "Cabaret Singer", character: "Jennifer Floreste", title: "41, American", tagline: "Previously starred at the London Palladium, a famous singer on her last voyage. Reports to the Entertainments Officer."},
  {email: "j@email.com", password: "teeth", faction_id: "2", role: "member", attendee: "party guest", character: "Sir Rory Canter", title: "Baronet, 54", tagline: "Rumoured to be the richest man in Great Britain."},
  {email: "k@email.com", password: "religion", faction_id: "2", role: "member", attendee: "party guest", character: "Lady Isabelle Canter", title: "33", tagline: "Young and pretty wife of Sir Rory, was previously an actress and ballet dancer."},
  {email: "l@email.com", password: "sister", faction_id: "2", role: "member", attendee: "party guest", character: "Jeremiah Finkelstein", title: "Industrial Businessman, 61", tagline: "Owner of several large American manufacturing concerns, as well as the first aircraft factory outside of Europe."},
  {email: "m@email.com", password: "milk", faction_id: "2", role: "member", attendee: "party guest", character: "Rachel Finkelstein", title: "Jeremiah’s wife and business partner, 58", tagline: "Rachel is renowned for her financial acumen."},
  {email: "n@email.com", password: "rifle", faction_id: "2", role: "member", attendee: "party guest", character: "PJ Nichols", title: "Singer, 27", tagline: "Although predominantly a Music Hall singer and entertainer, PJ has recently returned from Hollywood, after ‘trying out’ for several of the main studios."},
  {email: "o@email.com", password: "carpenter", faction_id: "2", role: "member", attendee: "party guest", character: "Clark Ridgeway", title: "PJ's Manager, 35", tagline: "Has arranged several stupendously successful shows and tours for PJ in the past."},
  {email: "p@email.com", password: "whistle", faction_id: "2", role: "member", attendee: "party guest", character: "Gilbert Ryce", title: "American Secretary of State, 68", tagline: "Ageing friend of the American President."},
  {email: "q@email.com", password: "company", faction_id: "2", role: "member", attendee: "party guest", character: "Wilma Drew", title: "Ryce's Assistant, 32", tagline: "Gilbert Ryce’s assistant in the American State Department, always smooth and unruffled."},
  {email: "r@email.com", password: "bumblebee", faction_id: "2", role: "member", attendee: "party guest", character: "Sir Ranulph Royston", title: "British Minister of War, 63", tagline: "A widower, Sir Ranulph’s wife recently died in a riding accident."},
  {email: "s@email.com", password: "channel", faction_id: "2", role: "member", attendee: "party guest", character: "Elizabeth James", title: "Sir Ranulph’s Daughter, 19", tagline: "Elizabeth is divorcing her husband after he had an affair."},
  {email: "t@email.com", password: "idea", faction_id: "2", role: "member", attendee: "party guest", character: "Maximillian von Grafenberg", title: "German Procurement Minister, 47", tagline: "Has been in America for the last year, and is now returning to Germany."},
  {email: "u@email.com", password: "volcano", faction_id: "2", role: "member", attendee: "party guest", character: "Armin Oberhausen", title: "Maximilian’s assistant, 39.", tagline: "Armin is ambitious and some say fancies the Maximilian’s job."},
  {email: "v@email.com", password: "battle", faction_id: "2", role: "member", attendee: "party guest", character: "Sasha Alexanderovich Ilyatkin", title: "Russian Minister, 45", tagline: "Sasha was in New York to sign trade agreements with the American Government."},
  {email: "w@email.com", password: "field", faction_id: "2", role: "member", attendee: "party guest", character: "Eldon Dumlop II", title: "American socialite, 47", tagline: "Rich American heir to the Dumlop rubber fortune."},
  {email: "x@email.com", password: "trouble", faction_id: "2", role: "member", attendee: "party guest", character: "Candice Dumlop", title: "American socialite and Eldon’s wife, 21", tagline: "Very glamorous and flirtatious rich American."},
  {email: "y@email.com", password: "step", faction_id: "2", role: "member", attendee: "party guest", character: "Marie Hati", title: "French journalist, 40", tagline: "Writes passionate columnes for Le Monde, demanding equal rights for women, and increased spending on hospitals."},
  {email: "z@email.com", password: "direction", faction_id: "2", role: "member", attendee: "party guest", character: "Aggie Marbles", title: "American, 26", tagline: "Aggie is travelling with the Finkelsteins. She has made a name for herself as an amateur sleuth."},
  ])

#
char_stories = CharStory.create!([
  {user_id: 1, char_story: 'aa'},
  {user_id: 2, char_story: 'bb'},
  {user_id: 3, char_story: 'a'},
  {user_id: 4, char_story: 'b'},
  {user_id: 5, char_story: 'c'},
  {user_id: 6, char_story: "You are a young prince from the neighboring kingdom of Dakhma. Since you are your father’s third son, you will not inherit the throne, so you have been training to someday become Captain of Dakhma’s Guard. A week ago, though, you were invited to a banquet where Princess Almeera’s father would choose her future husband. Your father thought that it was an amazing opportunity to inherit a throne, but that isn’t why you were keen. You have been in love with Princess Almeera since you used to play together as children. You have never told her how you feel, because you are worried she won’t feel the same way.\n\nThis morning you arrived at the Sultan’s palace, and met a prince named Amir Barad. Prince Amir Barad seemed overly confident that he would be chosen. The Grand Vizier seemed interested in you and in Prince Amir Barad, and spent time talking to each of you. However, when the dinner party started, the Sultan ignored you both: he spent all his time talking to a newly-arrived prince you had never seen before. His name was Prince Ala’ ad-Din, and he seemed arrogant. You noticed that he was cruel to the servants and worried that if he were chosen, he would mistreat the princess. While watching Prince Ala’ ad-Din, you noticed he had a bag he never let go of. You were curious what was in the bag, so you purposely bumped into him, and the bag fell to the floor. An old oil lamp poked out of the top of the bag. Prince Ala’ ad-Din quickly picked up the bag, stuffing the oil lamp back inside and called you a fool. You were left to wonder why the prince carried around an oil lamp – surely if he needed light, his servants should carry a lamp for him?\n\nWhen the Sultan announced that Prince Ala’ ad-Din would marry the princess, you knew you had to do something. You wrote the princess a letter telling her that you didn’t think it was fair that her father had not consulted with her before announcing the engagement. You invited her to meet you in the marketplace and run away to your kingdom, where she could negotiate with her father from a safe distance. You wrote that you just wanted to help, and she would have no obligation towards you. As you were about to sign your name, you stopped. Would Princess Almeera still come if she knew it was you? Both Ala’ ad-Din and Amir Barad were much more handsome... you signed the letter: Sincerely, Someone Who Cares. Then you stepped outside the banquet hall and gave the letter to a woman named Cantara, who was passing by, to deliver for you. You didn’t go back to dinner: instead, you packed your bags and headed to the marketplace to meet the princess.\n\nWhile you waited you let your thoughts wander. Last month, your brother returned from this city with a magic carpet, which he said he bought in this very marketplace. If Princess Almeera runs away with you, you’d like to take her on a magic carpet ride, and show her the sights of Dakhma. While you’re here you might as well try to find one for yourself, so you don’t have to borrow your brother’s. Magic carpets are illegal in this kingdom, so if you do get hold of one, you will have to keep it hidden. After a while you noticed that guards had surrounded the marketplace and the Grand Vizier had arrived. You heard whispered voices saying Princess Almeera’s fiancé had been murdered!\n\nIf Prince Ala’ ad-Din is dead, then you might still have a chance to be chosen as Princess Almeera’s fiancé! Maybe you should speak to the Grand Vizier and ask that he and the Sultan reconsider you. However, if things don’t turn out well and some other prince is chosen, the Princess may still want to run away with you. You don’t see her anywhere, but she might have disguised herself to sneak out of the palace. If the princess hasn’t come, you can at least stick close to Captain Hayat and learn how to be a good Captain of the Guards. You have heard rumors of a Band of Forty Thieves that haunts the alleyways at night: maybe the Captain can use your help in stopping them. You really hate thieves!"},
  {user_id: 7, char_story: 'd'},
  {user_id: 8, char_story: 'e'},
  {user_id: 9, char_story: 'f'},
  {user_id: 10, char_story: 'g'},
  {user_id: 11, char_story: 'h'},
  {user_id: 12, char_story: 'i'},
  {user_id: 13, char_story: 'j'},
  {user_id: 14, char_story: 'k'},
  {user_id: 15, char_story: 'l'},
  {user_id: 16, char_story: 'm'},
  {user_id: 17, char_story: 'n'},
  {user_id: 18, char_story: 'o'},
  {user_id: 19, char_story: 'p'},
  {user_id: 20, char_story: 'q'},
  {user_id: 21, char_story: 'r'},
  {user_id: 22, char_story: 's'},
  {user_id: 23, char_story: 't'},
  {user_id: 24, char_story: 'u'},
  {user_id: 25, char_story: 'v'},
  {user_id: 26, char_story: 'w'},
  {user_id: 27, char_story: 'x'},
  {user_id: 28, char_story: 'y'},
  {user_id: 29, char_story: 'z'},
  ])

#Create Goals
goals = Goal.create([
  {user_id: 6, goal_objective: "Find the Princess", goal_details: "Find out if the Princess is in the marketplace. If she is, convince her that you wrote the letter.", goal_achieved: 0},
  {user_id: 6, goal_objective: "Become Princess Almeera’s new fiancé", goal_details: "Convince the Vizier that you are the one who should marry Princess Almeera.", goal_achieved: 0},
  {user_id: 6, goal_objective: "Find a magic carpet", goal_details: "Find out who sells magic carpets, and buy one for yourself.", goal_achieved: 0},
  {user_id: 6, goal_objective: "Catch the murderer", goal_details: "Help the Grand Vizier and Captain Hayat catch the murderer. Learn from Hayat how a good Captain operates.", goal_achieved: 0},
  {user_id: 6, goal_objective: "Catch the Thieves", goal_details: "Help Captain Hayat catch the leader of the Band of Forty Thieves, and any other members who are identified.", goal_achieved: 0},
  {user_id: 1, goal_objective: "aa", goal_details: "aa", goal_achieved: 0},
  {user_id: 2, goal_objective: "bb", goal_details: "bb", goal_achieved: 0},
  {user_id: 3, goal_objective: "a", goal_details: "a", goal_achieved: 0},
  {user_id: 4, goal_objective: "b", goal_details: "b", goal_achieved: 0},
  {user_id: 5, goal_objective: "c", goal_details: "c", goal_achieved: 0},
  {user_id: 7, goal_objective: "d", goal_details: "d", goal_achieved: 0},
  {user_id: 8, goal_objective: "e", goal_details: "e", goal_achieved: 0},
  {user_id: 9, goal_objective: "f", goal_details: "f", goal_achieved: 0},
  {user_id: 10, goal_objective: "g", goal_details: "g", goal_achieved: 0},
  {user_id: 11, goal_objective: "h", goal_details: "h", goal_achieved: 0},
  {user_id: 12, goal_objective: "i", goal_details: "i", goal_achieved: 0},
  {user_id: 13, goal_objective: "j", goal_details: "j", goal_achieved: 0},
  {user_id: 14, goal_objective: "k", goal_details: "k", goal_achieved: 0},
  {user_id: 15, goal_objective: "l", goal_details: "l", goal_achieved: 0},
  {user_id: 16, goal_objective: "m", goal_details: "m", goal_achieved: 0},
  {user_id: 17, goal_objective: "n", goal_details: "n", goal_achieved: 0},
  {user_id: 18, goal_objective: "o", goal_details: "o", goal_achieved: 0},
  {user_id: 19, goal_objective: "p", goal_details: "p", goal_achieved: 0},
  {user_id: 20, goal_objective: "q", goal_details: "q", goal_achieved: 0},
  {user_id: 21, goal_objective: "r", goal_details: "r", goal_achieved: 0},
  {user_id: 22, goal_objective: "s", goal_details: "s", goal_achieved: 0},
  {user_id: 23, goal_objective: "t", goal_details: "t", goal_achieved: 0},
  {user_id: 24, goal_objective: "u", goal_details: "u", goal_achieved: 0},
  {user_id: 25, goal_objective: "v", goal_details: "v", goal_achieved: 0},
  {user_id: 26, goal_objective: "w", goal_details: "w", goal_achieved: 0},
  {user_id: 27, goal_objective: "x", goal_details: "x", goal_achieved: 0},
  {user_id: 28, goal_objective: "y", goal_details: "y", goal_achieved: 0},
  {user_id: 29, goal_objective: "z", goal_details: "z", goal_achieved: 0},
  ])

#Create Character Abilities
abilities = Ability.create!([
  {user_id: 1, power_name: "aa", power_desc: "aa", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 2, power_name: "bb", power_desc: "bb", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 3, power_name: "a", power_desc: "a", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 4, power_name: "b", power_desc: "b", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 5, power_name: "c", power_desc: "c", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 6, power_name: "It's just a flesh wound", power_desc: "When you would have been injured, use this Ability and you take no damage.", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 6, power_name: "Tell me your secrets", power_desc: "After speaking briefly and in a trustworthy manner to another player, show them this and they must show you their Secret.", quant_total: 3, quant_used: 0, quant_left: 3},
  {user_id: 6, power_name: "Let’s gossip!", power_desc: "After speaking briefly to another player, show them your Information and this Ability. They must show you their Information.", quant_total: 3, quant_used: 0, quant_left: 3},
  {user_id: 7, power_name: "d", power_desc: "d", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 8, power_name: "e", power_desc: "e", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 9, power_name: "f", power_desc: "f", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 10, power_name: "g", power_desc: "g", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 11, power_name: "h", power_desc: "h", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 12, power_name: "i", power_desc: "i", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 13, power_name: "j", power_desc: "j", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 14, power_name: "k", power_desc: "k", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 15, power_name: "l", power_desc: "l", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 16, power_name: "m", power_desc: "m", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 17, power_name: "n", power_desc: "n", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 18, power_name: "o", power_desc: "o", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 19, power_name: "p", power_desc: "p", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 20, power_name: "q", power_desc: "q", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 21, power_name: "r", power_desc: "r", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 22, power_name: "s", power_desc: "s", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 23, power_name: "t", power_desc: "t", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 24, power_name: "u", power_desc: "u", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 25, power_name: "v", power_desc: "v", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 26, power_name: "w", power_desc: "w", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 27, power_name: "x", power_desc: "x", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 28, power_name: "y", power_desc: "y", quant_total: 1, quant_used: 0, quant_left: 1},
  {user_id: 29, power_name: "z", power_desc: "z", quant_total: 1, quant_used: 0, quant_left: 1},
  ])

#Create Character secrets
char_secrets = CharSecret.create!([
  {user_id: 1, sec_desc: "aa"},
  {user_id: 2, sec_desc: "bb"},
  {user_id: 3, sec_desc: "a"},
  {user_id: 4, sec_desc: "b"},
  {user_id: 5, sec_desc: "c"},
  {user_id: 6, sec_desc: "You are your father’s third son, and your father wants you to become the Captain of the Guards. Marrying the princess is the only way you will get to rule a country."},
  {user_id: 7, sec_desc: "d"},
  {user_id: 8, sec_desc: "e"},
  {user_id: 9, sec_desc: "f"},
  {user_id: 10, sec_desc: "g"},
  {user_id: 11, sec_desc: "h"},
  {user_id: 12, sec_desc: "i"},
  {user_id: 13, sec_desc: "j"},
  {user_id: 14, sec_desc: "k"},
  {user_id: 15, sec_desc: "l"},
  {user_id: 16, sec_desc: "m"},
  {user_id: 17, sec_desc: "n"},
  {user_id: 18, sec_desc: "o"},
  {user_id: 19, sec_desc: "p"},
  {user_id: 20, sec_desc: "q"},
  {user_id: 21, sec_desc: "r"},
  {user_id: 22, sec_desc: "s"},
  {user_id: 23, sec_desc: "t"},
  {user_id: 24, sec_desc: "u"},
  {user_id: 25, sec_desc: "v"},
  {user_id: 26, sec_desc: "w"},
  {user_id: 27, sec_desc: "x"},
  {user_id: 28, sec_desc: "y"},
  {user_id: 29, sec_desc: "z"},
  ])

#Create Character Information
char_infos = CharInfo.create!([
  {user_id: 1, info_desc: "aa"},
  {user_id: 2, info_desc: "bb"},
  {user_id: 3, info_desc: "a"},
  {user_id: 4, info_desc: "b"},
  {user_id: 5, info_desc: "c"},
  {user_id: 6, info_desc: "The Princess received a note inviting her to run away with one of her suitors, and may now be here in the marketplace in disguise."},
  {user_id: 7, info_desc: "d"},
  {user_id: 8, info_desc: "e"},
  {user_id: 9, info_desc: "f"},
  {user_id: 10, info_desc: "g"},
  {user_id: 11, info_desc: "h"},
  {user_id: 12, info_desc: "i"},
  {user_id: 13, info_desc: "j"},
  {user_id: 14, info_desc: "k"},
  {user_id: 15, info_desc: "l"},
  {user_id: 16, info_desc: "m"},
  {user_id: 17, info_desc: "n"},
  {user_id: 18, info_desc: "o"},
  {user_id: 19, info_desc: "p"},
  {user_id: 20, info_desc: "q"},
  {user_id: 21, info_desc: "r"},
  {user_id: 22, info_desc: "s"},
  {user_id: 23, info_desc: "t"},
  {user_id: 24, info_desc: "u"},
  {user_id: 25, info_desc: "v"},
  {user_id: 26, info_desc: "w"},
  {user_id: 27, info_desc: "x"},
  {user_id: 28, info_desc: "y"},
  {user_id: 29, info_desc: "z"},
  ])

#Create Beginner Tips
beginner_tips = BeginnerTip.create!([
  {user_id: 1, advice: "aa"},
  {user_id: 2, advice: "bb"},
  {user_id: 3, advice: "a"},
  {user_id: 4, advice: "b"},
  {user_id: 5, advice: "c"},
  {user_id: 6, advice: "Talk to the young women in the marketplace (Joharra, Ara, Rasha, Nadia, and Zahrah) and try to find out if Princess Almeera is here. One of them might be the princess in disguise."},
  {user_id: 6, advice: "Tell Captain Hayat that you are training to be the Captain of the Guards in the kingdom of Dakhma, and ask if you can observe the investigations. Find out what you can do to help find the murderer."},
  {user_id: 7, advice: "d"},
  {user_id: 8, advice: "e"},
  {user_id: 9, advice: "f"},
  {user_id: 10, advice: "g"},
  {user_id: 11, advice: "h"},
  {user_id: 12, advice: "i"},
  {user_id: 13, advice: "j"},
  {user_id: 14, advice: "k"},
  {user_id: 15, advice: "l"},
  {user_id: 16, advice: "m"},
  {user_id: 17, advice: "n"},
  {user_id: 18, advice: "o"},
  {user_id: 19, advice: "p"},
  {user_id: 20, advice: "q"},
  {user_id: 21, advice: "r"},
  {user_id: 22, advice: "s"},
  {user_id: 23, advice: "t"},
  {user_id: 24, advice: "u"},
  {user_id: 25, advice: "v"},
  {user_id: 26, advice: "w"},
  {user_id: 27, advice: "x"},
  {user_id: 28, advice: "y"},
  {user_id: 29, advice: "z"},
  ])

#Create Other People
other_people = OtherPerson.create!([
  {user_id: 1, lead_name: "aa",lead_info: "a"},
  {user_id: 2, lead_name: "bb",lead_info: "b"},
  {user_id: 3, lead_name: "a", lead_info: "a"},
  {user_id: 4, lead_name: "b", lead_info: "b"},
  {user_id: 5, lead_name: "c", lead_info: "c"},
  {user_id: 6, lead_name: "Captain Hayat", lead_info: "You view the Captain as a role model. Hayat is very strict and efficient with the guards. Someday you may become the Captain of the Guards in Dakhma, and you can learn a lot from Hayat."},
  {user_id: 6, lead_name: "Abdul-Malik", lead_info: "The Grand Vizier is the Sultan’s most trusted friend. He is loyal to the Sultan and Princess Almeera. He has known and liked you since you were a child, but he would probably not like the fact that you were planning on sneaking away with the Princess."},
  {user_id: 6, lead_name: "Joharra", lead_info: "This young woman looks vaguely familiar. You wonder where you might have seen her before."},
  {user_id: 6, lead_name: "Cantara", lead_info: "Cantara is the woman who delivered your message to Princess Almeera. You liked Cantara, though she seemed a little absentminded."},
  {user_id: 6, lead_name: "Adi", lead_info: "While visiting Ardalan when you were young, Adi used to play with you and the princess. Adi is now working as a guard – much as you will be, if you do not marry Princess Almeera."},
  {user_id: 7, lead_name: "d", lead_info: "d"},
  {user_id: 8, lead_name: "e", lead_info: "e"},
  {user_id: 9, lead_name: "f", lead_info: "f"},
  {user_id: 10, lead_name: "g", lead_info: "g"},
  {user_id: 11, lead_name: "h", lead_info: "h"},
  {user_id: 12, lead_name: "i", lead_info: "i"},
  {user_id: 13, lead_name: "j", lead_info: "j"},
  {user_id: 14, lead_name: "k", lead_info: "k"},
  {user_id: 15, lead_name: "l", lead_info: "l"},
  {user_id: 16, lead_name: "m", lead_info: "m"},
  {user_id: 17, lead_name: "n", lead_info: "n"},
  {user_id: 18, lead_name: "o", lead_info: "o"},
  {user_id: 19, lead_name: "p", lead_info: "p"},
  {user_id: 20, lead_name: "q", lead_info: "q"},
  {user_id: 21, lead_name: "r", lead_info: "r"},
  {user_id: 22, lead_name: "s", lead_info: "s"},
  {user_id: 23, lead_name: "t", lead_info: "t"},
  {user_id: 24, lead_name: "u", lead_info: "u"},
  {user_id: 25, lead_name: "v", lead_info: "v"},
  {user_id: 26, lead_name: "w", lead_info: "w"},
  {user_id: 27, lead_name: "x", lead_info: "x"},
  {user_id: 28, lead_name: "y", lead_info: "y"},
  {user_id: 29, lead_name: "zed", lead_info: "zed"},
  ])

#Create Game Rules
game_rules = GameRule.create!([
  {rule_name: "The Genie’s Word is Law", rule_desc: "The Genie is impartial. If you have a problem or want to do something unusual, see the Genie. The Genie’s power is absolute – and cannot be affected by Abilities!"},
  {rule_name: "Winning and Losing", rule_desc: "You can achieve most of your goals simply by talking to people. The Genie will announce when the game is over. If you haven’t succeeded by that point – you’re too late! Be warned – not everyone here will want you to succeed!"},
  {rule_name: "Doing Stuff", rule_desc: "Ordinary actions are resolved by simply carrying them out. If you want to try something unusual (such as leap up onto a market stall), see the Genie. The Genie knows everything – and will be able to tell you the outcome of whatever it is that you are trying to do. (For example, the stall may be too flimsy.) Do use your imagination, though! – this is a very flexible game, and you can do all sorts of things beyond what’s listed in these rules."},
  {rule_name: "Fighting", rule_desc: "Ardalan can be a dangerous place! Your character may wish to grapple with, come to blows with, or even stab one of the other characters. Should you wish to do something along these lines though, don’t just dive in! See the Genie first and tell them what you plan to do so they can oversee and give you more detailed rules if it’s necessary."},
  {rule_name: "Leaving the Marketplace", rule_desc: "The Sultan’s guard has surrounded the marketplace, and no-one will be allowed to leave until the murderer is found and arrested. Anyone attempting to leave will be killed, no questions asked."},
  {rule_name: "Item Cards", rule_desc: "Any items of importance within the game are represented as Item cards – and the only items that can affect the game are those detailed on the cards. If you do not have an Item card, you do not have that item with you."},
  {rule_name: "Time", rule_desc: "Arabian Nights is played over three hours, with extra time for reading your character etc. There will be breaks to get drinks and food! The Genie will tell you when each period starts and finishes."},
  ])
